// <auto-generated />
namespace YAT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class manytomanyrelationisbad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manytomanyrelationisbad));
        
        string IMigrationMetadata.Id
        {
            get { return "201504150737510_many to many relation is bad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
